name: Pull Request Worflow
on:
  pull_request:
    branches:
      - main

jobs: 
# Job Test unitaire
  test-unitaires:
    runs-on: ubuntu-latest
    steps:
      - name: Recuperation du repo
        uses: actions/checkout@v2

      - name: Recuperation de Node.js
        uses: actions/setup-node@v2

      - name: Installation dépendances
        run: npm install

      - name: Run les test
        run: npm test
# # 2eme job, build de l'image docker
#   creation-image-docker:
#     runs-on: ubuntu-latest
#     needs: test-unitaires
#     steps:
#       - name: Recuperation du repo
#         uses: actions/checkout@v2

#       - name: Recuperation de Node.js
#         uses: actions/setup-node@v2

#       - name: Installation des dépendances
#         run: npm install

#       - name: Build de l'image
#         run: npm run build
# Job Push de l'image sur le docker hub
  push-image:
    runs-on: ubuntu-latest
    needs: test-unitaires
    steps:
    - name: Recuperation du repo
      uses: actions/checkout@v2

    - name: Installation QEMU
      uses: docker/setup-qemu-action@v1

    - name: Installation Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Connection à DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build et push mon image docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bricedo/exo-weather-docker:latest