name: Push Workflow
on:
  push:
jobs:
  test-unitaires:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Run les test
        run: npm install
        run: npm test