name: Push Workflow
on:
  push:
jobs:
  test-unitaires:
  runs-on: ubuntu-latest
  steps:
    - name: recuperation du repo
      uses: actions/checkout@v2
    - name: recuperation de node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - name: Run les test
      - run: npm test