name: Push Workflow
on:
  push:
jobs:
  test-unitaires:
  runs-on: ubuntu-latest
  steps:
    - name: recuperation de node
      uses: actions/setup-node@v2
    - name: Run les test
      - run: npm install
      - run: npm test